#+TITLE: My Emacs Config
#+AUTHOR: Paul M Lambert [[mailto:lambertington@gmail.com][lambertington@gmail.com]]
#+STARTUP: hidestars
#+PROPERTY: header-args:emacs-lisp :tangle yes

Below is my Emacs configuration with [[info:org#Working with source code][documentation of what it does].

* Header
I include this library to ensure full Common Lisp functionality.

#+BEGIN_SRC emacs-lisp
  (require 'cl)
#+END_SRC

* Personal Information
I know Emacs -- it's only fair that Emacs knows me!

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Paul M Lambert"
        user-mail-address "lambertington@gmail.com")
#+END_SRC

* Setting up the package manager
** Add package sources
The default repos are pretty limited in their selection of packages, so let's add some better ones.

#+BEGIN_SRC emacs-lisp
  ;;; initialize package manger
  (require 'package)
  (setq package-archives '(("melpa" . "http://melpa.milkbox.net/packages/")
                           ("org" . "http://orgmode.org/elpa/")
                           ("gnu" . "http://elpa.gnu.org/packages/")))

  (package-refresh-contents)
#+END_SRC

You'll need to use =M-x package-refresh-contents= to reload the list of packages after adding these for the first time.

** Adding use-package.el
[[https://github.com/jwiegley/use-package][use-package.el]] is a life saver for handling dependencies, especially if you use multiple machines. Check it out.

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (setq use-package-verbose t)

  (require 'use-package)
  (use-package auto-compile
    :ensure t
    :init (auto-compile-on-load-mode))
  (setq load-prefer-newer t)
#+END_SRC

* General settings
** Aesthetics
With as much time as you spend in an editor, it's important to modify the looks to your pleasure!

Hiding the menu, tool, and scroll bars

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+END_SRC

Let's go ahead and enable our preferred color scheme, Zenburn

#+BEGIN_SRC emacs-lisp
  (add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
  (load-theme 'zenburn t)
#+END_SRC

** Global settings

Change yes-or-no prompts to y-or-n, because typing that much that frequently is awful!

#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Switch from tabs to spaces for all files... tabs are worthless..

#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

Let's disable the nasty startup messages and go straight to the \*scratch\* buffer

#+BEGIN_SRC emacs-lisp
  (setq inhibit-splash-screen t
        inhibit-startup-echo-area-message t
        inhibit-startup-message t)
#+END_SRC

Enable line/col numbers on all files

#+BEGIN_SRC emacs-lisp
  (line-number-mode t)
  (column-number-mode t)
  (global-linum-mode t)
#+END_SRC
